url: "https://www.florentweillaert.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "florentweillaert.com" # the subpath of your site, e.g. /blog
title: "Florent Weillaert" # the name of your site, e.g. ACME Corp.
